// A payload written for the assertions, not harvested from anywhere.
//
// The board's own `data/` is regenerated by CI's harvest step before the tests run,
// and its counts move every time a puck lands — so a test that asserted "Done 102"
// against it would be measuring the roadmap, not the code. Everything here is chosen
// to exercise a rule: two repos where one is entirely archived (so it becomes a whole
// hidden column), a cancelled puck and an empty cancelled case, an etapp with one
// member, and two target months of which one holds only archived pucks.
const REPOS = [
  { repo: "acme/alpha", name: "Alpha", color: "#e07a5f" },
  { repo: "acme/beta", name: "Beta", color: "#3d8fd1" },
  { repo: "acme/landed", name: "Landed", color: "#6bbf8a" },
];

function puck(o) {
  return {
    id: o.repo.split("/")[1] + "/" + o.slug,
    repo: o.repo,
    repoName: REPOS.filter(function (r) { return r.repo === o.repo; })[0].name,
    repoColor: REPOS.filter(function (r) { return r.repo === o.repo; })[0].color,
    slug: o.slug,
    title: o.title || o.slug,
    status: o.status,
    priority: o.priority || null,
    tags: o.tags || [],
    updated: o.updated || "2026-08-20",
    created: "2026-08-01",
    target: o.target || null,
    issue: null,
    issueState: null,
    order: o.order || 10,
    depends: [],
    blockedBy: [],
    blocks: [],
    missingDepends: [],
    parent: o.parent || null,
    parentRef: o.parentRef || null,
    children: o.children || [],
    progress: o.children ? { done: 0, total: o.children.length } : null,
    owner: null,
    agent: o.agent || null,
    body: "Body of " + o.slug,
    sourcePath: "roadmap/" + o.slug + ".md",
    sourceUrl: "https://example.invalid/" + o.slug,
    adapter: "pucks",
    native: true,
    signals: [],
  };
}

export const ITEMS = [
  // Alpha: one of each live status, plus an etapp and its member.
  puck({ repo: "acme/alpha", slug: "a-now", status: "now", tags: ["ui"] }),
  puck({ repo: "acme/alpha", slug: "a-now-2", status: "now", priority: "high" }),
  puck({ repo: "acme/alpha", slug: "a-next", status: "next", target: "2026-05-31" }),
  puck({ repo: "acme/alpha", slug: "a-later", status: "later", agent: "backend" }),
  puck({ repo: "acme/alpha", slug: "a-inbox", status: "inbox" }),
  puck({ repo: "acme/alpha", slug: "a-done", status: "done", target: "2026-03-31" }),
  puck({ repo: "acme/alpha", slug: "a-cancelled", status: "cancelled", target: "2026-03-31" }),
  puck({
    repo: "acme/alpha", slug: "a-etapp", status: "now", title: "An etapp",
    children: ["beta/b-member"],
  }),
  // Beta: a member of Alpha's etapp, and two archived pucks.
  puck({
    repo: "acme/beta", slug: "b-member", status: "next",
    parent: "acme/alpha#a-etapp", parentRef: "alpha/a-etapp",
  }),
  puck({ repo: "acme/beta", slug: "b-later", status: "later", tags: ["ui", "dx"] }),
  puck({ repo: "acme/beta", slug: "b-done", status: "done" }),
  // Landed: every puck archived, so the whole repo column is archive-hidden.
  puck({ repo: "acme/landed", slug: "l-done", status: "done" }),
];

export const PAYLOAD = {
  generatedAt: "2026-08-27T00:00:00.000Z",
  statuses: ["now", "next", "later", "inbox", "done", "cancelled"],
  counts: {},
  total: ITEMS.length,
  sources: REPOS.map(function (r) {
    return { repo: r.repo, name: r.name, color: r.color, adapter: "pucks", count: 0 };
  }),
  items: ITEMS,
  config: { title: "Test board", description: "", repoUrl: "https://github.com/acme/alpha", views: [] },
};

